version: 0.0
os: linux
files:
  - source: webapp.tar.gz
    destination: /home/centos/
hooks:
  BeforeInstall:
    - location: infrastructure/aws/codedeploy/stop_server.sh
      runas: centos
      timeout: 180
  AfterInstall:
    - location: infrastructure/aws/codedeploy/afterInstall.sh
      runas: centos
      timeout: 180
  ApplicationStart:
    - location: infrastructure/aws/codedeploy/start_server.sh
      timeout: 3600
      runas: centos
       