version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - checkout
      - run:
          name: Install packages
          command: |
            sudo apt-get update && sudo apt-get install wget zip unzip python-pip -y

      - run:
          name: Install awscli
          command: sudo pip install awscli

      - run:
          name: Build and Zip Artifact
          command: |
            echo "Hello the current build number is ${CIRCLE_BUILD_NUM}"
            pwd
            ls -al
            mkdir -p codedeploy_artifact
            #zip -r webapp.zip webapp/
            tar -czvf webapp.tar.gz webapp/ infrastructure/aws/cloudformation/amazon-cloudwatch-config.json
            #zip -r csye6225-webapp-${CIRCLE_BUILD_NUM}.zip webapp.zip .yml infrastructure/aws/codedeploy/
            tar -czvf csye6225-webapp-${CIRCLE_BUILD_NUM}.tar.gz webapp.tar.gz *.yml infrastructure/aws/codedeploy/*
            mv csye6225-webapp-${CIRCLE_BUILD_NUM}.tar.gz codedeploy_artifact
            ls -al
            cd ..
            echo "................"    

      - run:
          name: Upload Artifact to S3
          command: |
            pwd
            ls -al
            cd codedeploy_artifact
            aws configure list
            aws s3 cp csye6225-webapp-${CIRCLE_BUILD_NUM}.tar.gz s3://${s3bucket}
             #aws s3 sync codedeploy_artifact s3://${s3bucket}      

      - run:
          name: Make CodeDeploy API call
          command: |
            echo "Hello CodeDeploy"
            echo "Testing" 
            aws deploy create-deployment --region us-east-1 --application-name csye6225-webapp --deployment-group csye6225-webapp-deployment --s3-location bucket=${s3bucket},key=csye6225-webapp-${CIRCLE_BUILD_NUM}.tar.gz,bundleType=tgz